export * from './destination.reducer';
export * from './spots.reducer';
export * from './nearbyspots.reducer';
export * from './tutorial.reducer';
export * from './places.reducer';
export * from './appmode.reducer';
export * from './addspotstep.reducer';
export * from './reportspotstep.reducer';
export * from './spotslistmode.reducer';
